apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dotnet
  namespace: argocd
spec:
  project: default
  source:
   chart: sample-dotnet
   repoURL:  ghcr.io/zs-amrutha
   targetRevision: 0.1.0
   helm:
    releaseName: quixy-web    
  destination:
       server: "https://kubernetes.default.svc"
       namespace: "dotnet"
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true