apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dotnet
  template:
    metadata:
      labels:
        app: dotnet
    spec:
      containers:
      - name: dotnet
        image: ghcr.io/zs-amrutha
        ports:
        - containerPort: 5000