apiVersion: v1
kind: Service
metadata:
  name: dotnet-service
  labels:
    app: dotnet-service
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: dotnet
