name: build and push helm chart
on:
  push:
    branches:
      - 'master'
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - name: 'Checkout'
         uses: actions/checkout@v2
       - name: 'cloning repo'
         uses: actions/checkout@v2
       - name: 'build and push helm chart'
         run: |
          export HELM_EXPERIMENTAL_OCI=1
          export GITHUB_TOKEN =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
          echo $GITHUB_TOKEN | helm registry login https://ghcr.io --username zs-amrutha --password-stdin
          cd helm
          helm package .
          helm push *.tgz oci://ghcr.io/zs-amrutha
  
